# Generated by Django 6.0.6 on 2026-06-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_categoria_post_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='name',
        ),
    ]
